### PR TITLE
Skate additions 

### PR DESCRIPTION
**Pull request by SWerner2**
Skate additions from FW 12 RFA review

### CODE REVIEW

**Comment by SWerner2** [comment]
@mle2718 Let me know if this meets your requirements.

**Review by mle2718 — APPROVED** [review]

**Comment by mle2718** [comment]
@SWerner2  -- is this always going to be true for all skate actions, or is it something that is going to need to be looked at every time?

**Comment by SWerner2** [comment]
From my

> @SWerner2 -- is this always going to be true for all skate actions, or is it something that is going to need to be looked at every time?

From my understanding this is the new standard. Given that the RFA code is generated the same way, the logic for this conclusion holds.

**Comment by mle2718** [comment]
Thanks @SWerner2 . I will merge and make a couple small formatting changes.

**Pull request merged**
